import { Inter } from "next/font/google";
import "../app/globals.css";
import "../assets/styles/main.scss";
import "react-loading-skeleton/dist/skeleton.css";
import Header from "@/components/modules/header";
import Footer from "@/components/modules/footer";
import LazyImage from "@/components/modules/lazyImage";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer /> 
      </body>
    </html>
  );
}
